# Generated by Django 4.1 on 2022-10-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listings_comments_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='imgurl',
            field=models.TextField(),
        ),
    ]
