# Generated by Django 4.1 on 2022-10-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listings_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.IntegerField(default=0),
        ),
    ]
