# Generated by Django 4.1 on 2022-10-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bids_bid_alter_listings_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='maxbid',
            field=models.FloatField(default=0),
        ),
    ]
