# Generated by Django 4.1 on 2022-10-27 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listings_maxbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
